### ISSUE TITLE
Feature request: supply Postgres script to delete fields in main database before a certain date

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#108]
IT has become apparent we will at various points have to purge old information out of the decision engine database.  Please supply an appropriate script to delete
all records created before date x.

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/175

**Comment by StevenCTimm** [comment]
Installed on hepcsvc03 which has a database that goes back to April 9.

    'dataspace': {
        'retention_interval_in_days' : 365,
        'datasource' : {

adding the retention interval in days parameter.

Then ran /usr/bin/de-reaper from the command line

Had 25687067 entries in dataproduct and metadata tables when we started.

**Comment by StevenCTimm** [comment]
Trimmed down to 24005433 records
Oldest time stamp now on May 3 2019.
Declare success on this.
Issue can be closed.
