### ISSUE TITLE
configure_gwms_frontend.py execution error in new 1.1.0-py27 rpm 

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#207]
Part of preparing to configure the decision engine is to execute the command:

python /usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/configure_gwms_frontend.py

In the new version that command now exits with the following error message:
python /usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/configure_gwms_frontend.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/decisionengine_modules/glideinwms/configure_gwms_frontend.py", line 16, in <module>
    from . import glideinwms_config_lib
ValueError: Attempted relative import in non-package

---

Line 16 in the new version reads

from . import glideinwms_config_lib

Previously it read 

import glideinwms_config_lib

How do we get past this--is there a configuration step that has to be done to make the local directory (...decisionengine_modules/glideinwms/ ) a python package?

**Comment by StevenCTimm** [comment]
Removing the 'from .' from line 16 got me past that error and the configure_gwms_frontend.py script now executes successful

**Comment by StevenCTimm** [comment]
Evidently there are more of these in the python 2.7 we will find them as we execute.

**Comment by hyunwoo18** [comment]
Steve, what do you mean, "Evidently there are more of these.."?
Dmitry showed that this command
 find ./ -name '*.py' -exec egrep -H '^from \. import' {} \; 
returns just one (configure_gwms_frontend.py)..

**Comment by StevenCTimm** [comment]
The test rpms that were made from Dmitry's PR worked ok and we can now configure the frontend.
