### ISSUE TITLE
decisionengine-standard-library-1.1.0-py36.rpm puts files in wrong place

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#212]
The initial releases of decisionengine-standard-library-1.1.0-py36.rpm 
was putting all of its files into /usr/lib/python2.7/site-packages instead of 
/usr/lib/python3.6/site-packages.

(carried over from https://github.com/HEPCloud/decisionengine/issues/78 where it was first reported)

**Comment by gartung** [comment]
https://github.com/HEPCloud/decisionengine_modules/pull/211

**Comment by gartung** [comment]
Can't link the PR since I don't have admin.

**Comment by gartung** [comment]
Artifacts link
https://github.com/HEPCloud/decisionengine_modules/suites/619973892/artifacts/4876446

**Comment by StevenCTimm** [comment]
OK the artifacts generated from PR #211 have the correct rpm structure.. thank you.
Whether they actually start and work, we will track in a separate ticket.
