### ISSUE TITLE
Branch 1.2.0 python3.6 BillingInfo.py not correctly fetching billing files from AWS

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#240]
Although the AWSbilling channel is showing STEADY and always has shown STEADY ever since I started testing the python3 1.2 branch, closer examination revealed that it has not in fact downloaded any billing information from AWS at all.

The python 2.7 branch 1.1.x works OK

I am not yet sure if this is a configuration error or a problem in the underlying code.  Issue #198 is closely related to this..an old one in which the channel showed STEADY even though it was missing libraries that it should be importing.  In any case many too many exceptions are caught in this routine including whichever one we are hitting at the moment.

**Comment by StevenCTimm** [comment]
this may be a case of python not able to find the boto3 library in the python path.. that is what I get when I try to run interactively.  pip3 installs stuff in /usr/local/lib/python3.6.
Have enabled the debug and verbose flags in this routine and trying to see if I can get more info...whatever exception is happening is happening very early before it downloads any of the files.

**Comment by StevenCTimm** [comment]
I note also that the commented out print statements in BillingInfo.py are not python-3 compatible, when I tried to uncomment them I found that out.

**Comment by StevenCTimm** [comment]
It's sort of nasty trying to debug this because every time you restart the channel it goes back to INFO debug level and it dies before you can set it to DEBUG and get all the DEBUG level statements to print out.  In any case the routine is dying almost immediately when the acquire command is called, in less than a second.

**Comment by DmitryLitvintsev** [comment]
> I note also that the commented out print statements in BillingInfo.py are not python-3 compatible, when I tried to uncomment them I found that out.

commented code needs to be excised.

**Comment by DmitryLitvintsev** [comment]
what machine are you on? I can make it permanent DEBUG foe you there

**Comment by DmitryLitvintsev** [comment]
> this may be a case of python not able to find the boto3 library in the python path.. that is what I get when I try to run interactively. pip3 installs stuff in /usr/local/lib/python3.6.
> Have enabled the debug and verbose flags in this routine and trying to see if I can get more info...whatever exception is happening is happening very early before it downloads any of the files.

```
[root@fermicloud117 ~]# python3
Python 3.6.8 (default, Apr  1 2020, 10:29:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> 
```

**Comment by StevenCTimm** [comment]
fermicloud117 is the machine.  it appears that it is indeed getting as far as the acquire 
and then doing nothing because the self.accounts variable is blank.

2020-06-09 20:31:44,449 - root - TaskManager - 2142 - BillingInfo - INFO - Src BillingInfo calling acquire
2020-06-09 20:31:44,452 - root - BillingInfo - 2142 - BillingInfo - DEBUG - accounts: []
2020-06-09 20:31:44,458 - root - TaskManager - 2142 - BillingInfo - INFO - Src BillingInfo acquire retuned
2020-06-09 20:31:44,459 - root - TaskManager - 2142 - BillingInfo - INFO - Src BillingInfo filling header
2020-06-09 20:31:44,459 - root - TaskManager - 2142 - BillingInfo - INFO - Src BillingInfo header done

**Comment by DmitryLitvintsev** [comment]
in fact all imports used by BillinInfo.py check out without errors:

```
[root@fermicloud117 ~]# python3
Python 3.6.8 (default, Apr  1 2020, 10:29:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import copy
>>> import csv
>>> import datetime
>>> import io
>>> import logging
>>> import os
>>> import pprint
>>> import re
>>> import string
>>> import time
>>> import zipfile
>>> 
>>> import boto3

>>> import pandas as pd
>>> from boto3.session import Session
>>> 
>>> from decisionengine.framework.modules import Source
>>> from decisionengine_modules.AWS.sources import DEAccountContants
>>> 
```

**Comment by StevenCTimm** [comment]
ok--just forgot that stock python on fermicloud117 is not yet python3 so that is understood.

**Comment by StevenCTimm** [comment]
There is some discussion on this in the logging issue in the framework by mistake.
Dmitry figured out why the Accounts field was blank--there was an exec that had to 
had different arguments.. I have found 2 exceptions since then and now stuck at 

20-06-09 22:09:33,312 - root - TaskManager - 5085 - BillingInfo - ERROR - Exception running source BillingInfo : module 'string' has no attribute 'rstrip'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/AWS/sources/BillingInfo.py", line 682, in acquire
    lastStartDateBilledConsideredDatetime, CorrectedBillSummaryDict = calculator.CalculateBill()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/AWS/sources/BillingInfo.py", line 112, in CalculateBill
    fileNameForDownloadList)
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/AWS/sources/BillingInfo.py", line 430, in _billingDataByMonth
    billingFileName = string.rstrip(zipFileName, '.zip')
AttributeError: module 'string' has no attribute 'rstrip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/decisionengine/framework/taskmanager/TaskManager.py", line 299, in run_source
    data = src.worker.acquire()
  File "/usr/lib/python3.6/site-packages/decisionengine_modules/AWS/sources/BillingInfo.py", line 754, in acquire
    raise Exception(detail)
Exception: module 'string' has no attribute 'rstrip'

**Comment by DmitryLitvintsev** [comment]
Fixed on fermicloud117  Restart decision engine.
