### ISSUE TITLE
module uses a tuple as configuration parameter, this is not allowed for jsonnet configuration

### ISSUE THREAD

**Issue by vitodb** [HEPCloud/decisionengine_modules#251]
The module
decisionengine_modules/glideinwms/transforms/job_clustering.py
has the configuration parameter `match_expressions` that uses a tuple as key.
This is not allowed for jsonnet configuration files.
The code needs to be changed to use single element key.

**Comment by StevenCTimm** [comment]
This was already tracked in issue #244--there is no functional reason why the code in question can't use a single element key and if so, the key should be the group_name.

**Comment by StevenCTimm** [comment]
This issue is now a blocking issue that is keeping us from doing further testing.

**Comment by StevenCTimm** [comment]
Vito has a modified version of the code but it is dying with an exception.

**Comment by StevenCTimm** [comment]
Fixed in 1.3.0rc1 with the exception of the problem when RequestMaxInputRate is Nan or DESIRED_Sites is Nan.

**Comment by StevenCTimm** [comment]
1.3.0 version is cut and includes this fix.  Closing this issue.
