### ISSUE TITLE
Different modules are using different retry parameters in config

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#253]
source_proxy uses 
retries=3

publishers are using 
nretries

sources (such as NerscAllocationInfo) are using max_retries

Should make them all uniform.

**Comment by StevenCTimm** [comment]
This is an issue that borders both on the framework and the modules and perhaps can be addressed in the configuration work that Kyle and Vito are doing.

**Comment by StevenCTimm** [comment]
Note that on source proxies the retry delay that is specified seems to be being ignored.

Steve Timm

**Comment by knoepfel** [comment]
There is an issue of naming, and then there is one of meaning:

1. I think `max_retries` best connotes what the parameter means--i.e. this is the maximum number of retries allowed before the function/method "gives up."  I'll therefore go that direction.
2. The `retries` parameter for the `SourceProxy`, however, is interpreted by the code to mean the maximum number of **attempts**, not retries.  For the `SourceProxy`, therefore, I suggest:
  a. Changing the parameter name to `max_attempts` to reflect current behavior, or 
  b. Changing it to `max_retries`, but then adjusting the `SourceProxy` code to interpret that as retries and not attempts.

@StevenCTimm, do you have an opinion on (1), (2a), or (2b) above?
