### ISSUE TITLE
Add option to config of condor/sources/job_q.py and slots.py 

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#255]
There are continuing problems with exceptions that come because one value or the other in the job_manifests data block or the Factory_Entries blocks is not of the expected type.

We need a way to specify in the configuration, which columns should be forced to string and which modules should be forced to int.  (in theory there are also columns that are float and bool).
We should have the option to specify which type, and which default value to use if necessary.

**Comment by hyunwoo18** [comment]
I have come up with a simple solution to take care of 2 specific attributes (Desired_OS and RequestMaxInputRate)
and asked Steve to see if this patch helps in fermicloud177.

**Comment by StevenCTimm** [comment]
1. Go to /usr/lib/python3.6/site-packages/decisionengine_modules/htcondor/sources.
   You will find a new file, hk_job_q.py, a copy of job_q.py.
   I put two new lines in hk_job_q.py.

   df[['RequestMaxInputRate']] = df[['RequestMaxInputRate']].fillna(value=0)
   df[['DesiredOS']] = df[['DesiredOS']].fillna(value='')

   I have been looking for a way to specify types column-by-column when creating a dataframe
   but according to the official pandas manual, pandas.DataFrame constructor 
   permits just one type for all entries,
   which is ridiculous.
  (https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.html)

   So, I am applying fillna method to 'RequestMaxInputRate' and 'DesiredOS' separately
   with a value 0 and empty string respectively.
   Note that this is after a dataframe has been created from a dictionary from condor python call.

   So,  move job_q.py to job_q.org and cp hk_job_q.py to job_q.py.

2. Then, open
 /usr/lib/python3.6/site-packages/decisionengine_modules/glideinwms/transforms/job_clustering.py
and change in tramsform method:

from
 df_q = df_full_q.fillna('').query( self.job_q_expr )
to
 df_q = df_full_q.query( self.job_q_expr )

3. No change is needed to the config file for this test.

4. And submit those rogue jobs
   and see if my recipe solves the exceptions.

Note that this simple changes might not be a perfect solution, 
namely I might have to do a deeper research into DataFrame constructors
but let's first see if these changes can be a starting point.

Thanks,
HyunWoo

**Comment by StevenCTimm** [comment]
Following test process was done:
I started from clean 1.3.0-1 release on fermicloud117 and verified that all channels were functional (except job_classification)

 diff hk_job_q.py job_q.py
54,57d53
< ## HK Begin
<                     df[ ['RequestMaxInputRate'] ] = df[ ['RequestMaxInputRate'] ].fillna(value=0)
<                     df[ ['DesiredOS']           ] = df[ ['DesiredOS']           ].fillna(value='')
< ## HK end

Made the changes in job_clustering.py as described.  Same change has to be made to glideinwms/glide_frontend_element.py

Restarted the DE

There were already rogue jobs in the queue ( of the type with RequestMaxInputRate == Nan )

The first time through we did get an exception (although it is caught)

2020-08-06 09:18:10,029 - root - job_clustering - 2682 - JobClustering - ERROR - Unable to calculate totals from job manifests, may have missing classads or incorrect classad names

This is the stock exception when DESIRED_Sites = Nan and that is what we see when we dump the data block 

de-client --print-product job_manifests --columns DESIRED_Sites,RequestMaxInputRate
Product job_manifests:  Found in channel job_classification
+----+-----------------+-----------------------+
|    |   DESIRED_Sites |   RequestMaxInputRate |
|----+-----------------+-----------------------|
|  0 |             nan |                     0 |
|  1 |             nan |                     0 |
|  2 |             nan |                     0 |
|  3 |             nan |                     0 |
|  4 |             nan |                     0 |
+----+-----------------+-----------------------+


This is not surprising since the patch changed DesiredOS and not DESIRED_Sites.

Modified  hk_job_q accordingly:

Restarted full decision-engine again

Now job_manifests look like this
[root@fermicloud117 decisionengine]# de-client --print-product job_manifests --columns DESIRED_Sites,RequestMaxInputRate
Product job_manifests:  Found in channel job_classification
+----+-----------------+-----------------------+
|    | DESIRED_Sites   |   RequestMaxInputRate |
|----+-----------------+-----------------------|
|  0 |                 |                     0 |
|  1 |                 |                     0 |
|  2 |                 |                     0 |
|  3 |                 |                     0 |
|  4 |                 |                     0 |

And we do not get the previous exceptions

The five jobs in the queue were from Maria's test and had both DESIRED_Sites and RequestMaxInputRate undefined (translated to Nan) so they would not match any hep cloud resource.

I submit 200 jobs with DESIRED_Sites=="T3_US_NERSC" and RequestMaxInputRate undefined
(bucket1-nersc-new.jdl)

These are successfully recognized as making the cms_nersc_passthrough_sl7 bucket in the job_clusters bucket as they should.  They will now also match the bucket cms_all because we have made RequestMaxInputRate==0 and 
that makes the conditions for the cms_all bucket be true.


Now I submit 200 jobs (bucket1-allsites-sl7.jdl) with DESIRED_Sites undefined and RequestMaxInputRate==10

These should match the bucket cms_all--and they do.

So this technique gets us through the two immediate exceptions that we have recently observed.

The full set of variables that we currently select on  in job_q is the following:

VO (string)
CMS_JobType (string)
RequestCpus (int)
RequestMemory (float64)
MaxWallTimeMins (int)
RequestMaxInputRate (float64)
DESIRED_Sites (string)
REQUIRED_OS (string)
DesiredOS (string)
x509UserProxyVOName (string)
x509UserProxyFirstFQAN (string)
JOB_EXPECTED_MAX_LIFETIME (int)

The fields that we read in slots.py and use in comparisons are the following:

GlideinName. (string)
GLIDEIN_Supported_VOs. (string)
GLIDEIN_Max_Walltime  (int)
GLIDEIN_CPUS (int)
GLIDEIN_MaxMemMBs (float64)
GLIDEIN_REQUIRED_OS (string)
GLIDEIN_SITE (string)

The only two of the above that we have ever had problems with are GLIDEIN_CPUS
(which comes from the factory as string and then manually gets converted to int).  The code already handles this.

We filter out manually the values of GLIDEIN_CPUS that are not convertible to int, which are becoming
more as we go ("auto")
GLIDEIN_MaxMemMBs which comes from the factory as float but sometimes has unexpectedly been string.

So in general the test of this patch is good and it provides us a way to go forward for now but it would still be nice
to have this be configurable and not have to list every field that has to be converted explicitly in the code.

I acknowledge that it is also clunky to do that for a long line of variables like that and thus more research is necessary as Hyunwoo says above.

Steve Timm

**Comment by hyunwoo18** [comment]
Steve, I have been working on this ticket today.
I came up with a simple solution and have been testing it in my dev VM.
It seems to work, i.e. I do not see a crash even after my previous patch is removed when I deploy this new patch.

I will provide you with this patch tomorrow so that you can test this in your ITB (fermicloud117?) vm as well

**Comment by StevenCTimm** [comment]
OK let me know when it is ready.  Thanks.


Steve


________________________________

**Comment by hyunwoo18** [comment]
The procedure can simplified as	below:

1. Steve submits a job with JDL	file with Undefined

2. In htcondor/source/job_q.py:
```
condor_q = htcondor_query.CondorQ( schedd_name=schedd, pool_name=self.collector_host )
condor_q.load(constraint=self.constraint, format_list=self.classad_attrs, condor_config=self.condor_config)
df = pandas.DataFrame(  condor_q.stored_data  )
```
    This shows that	when the Condor sees an attribute that has "Undefined" as its value,
     we see this attribute in condor_q.stored_data have an None value.

3. And in the same htcondor/source/job_q.py:
  when pandas.DataFrame(  condor_q.stored_data  ) converts each item of condor_q.stored_data
  if this constructor pandas.DataFrame() detects a None value, it will	just put NaN in	the corresponding DataFrame.

4. So, then in glideinwms/transforms/job_clustering.py	
   when	we conduct a query against this dataframe that contains NaN for attributes like DesiredOS or RequestMaxInputRate,
   an exception	will be	raised because of these	NaN values in the dataframe..

**Comment by hyunwoo18** [comment]
I am going to open a merge request now and close the review request (https://fermicloud140.fnal.gov/reviews/r/210/) soon.

**Comment by StevenCTimm** [comment]
This is now deployed in production and I am closing this issue.
