### ISSUE TITLE
Migrate from boto to boto3

### ISSUE THREAD

**Issue by knoepfel** [HEPCloud/decisionengine_modules#259]
The GCEBillingInfo source uses the boto package, which is deprecated in favor of boto3.

**Comment by StevenCTimm** [comment]
Last time we tried to port that to boto3 we couldn't do it, there were other gce-specific sub packages which depended on boto and did not work with boto3.  But it should be investigated again.

**Comment by shreyb** [comment]
It appears as if the automatic closing of this issue from commit #258 was in fact correct.  I talked to @hyunwoo18 , and he agrees.  We'll bring this up at the developers' meeting and confirm with Dmitry and Steve.

**Comment by DmitryLitvintsev** [comment]
Yes indeed I find no "import boto" anywhere in our code. Now dependency on boto is in Maria's billing calculator library

**Comment by shreyb** [comment]
Great - I'll close this again.
