### ISSUE TITLE
Change DEAccountConstants.py to allow more variables through

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#283]
There is a hard-wired list of variables in DEAccountConstants.py.  It loads the file AccountConstants_my.py but only takes the variables in the hard-wired list to pass on to the main bill calculator routine.  We need to add the variable billingBucketName
to that list of variables, and possibly others.  (see issue #271 about the Logger field).

**Comment by StevenCTimm** [comment]
This is not a bug created by the project, it has always been this way.

**Comment by hyunwoo18** [comment]
Okay, this morning, I began to analyze this issue and 
here is my understanding:

The solution to Steve's request regarding  bucketBillingName is
```
update AWS/sources/DEAccountContants.py to add a new key, bucketBillingName 
(look at /etc/decisionengine/modules.conf/AccountConstants_my.py)
to EXPECTED_NAMES
```

Regarding Steve's second request about adding the logger also in EXPECTED_NAMES,
as can be seen in this code below, logger is already is taken care of
and need not be handled in the same way as bucketBillingName:

```
In oasistestgpvm2:/root/hknewde/decisionengine_modules/AWS/sources/BillingInfo.py
class BillingInfo(Source.Source):
    def __init__(self, *args, **kwargs):
.........
        self.logger = logging.getLogger()
..........
    def acquire(self):
        data = []
        datarate = []
        globalConf = {'graphite_host': 'dummy', 'graphite_context_billing': 'dummy', 'outputPath': self.billing_files_location, 'accountDirs': 1}
        for i in self.accounts:
            constantsDict = {'credentialsProfileName': i.credentialsProfileName, 'accountNumber': i.accountNumber,
                             'bucketBillingName': str(i.accountNumber) + '-dlt-utilization', 'lastKnownBillDate': i.lastKnownBillDate,
                             'balanceAtDate': i.balanceAtDate, 'applyDiscount': i.applyDiscount}
            try:
                calculator = AWSBillCalculator(i.accountName, globalConf, constantsDict, self.logger)
```

In conclusion, I will just update AWS/sources/DEAccountContants.py to add bucketBillingName in EXPECTED_NAMES
and create a review this PM.

**Comment by hyunwoo18** [comment]
https://fermicloud140.fnal.gov/reviews/r/308/

**Comment by hyunwoo18** [comment]
I tested this changes in fermicloud155 with Steve
and Steve confirms that the patches are effective.
I will merge after lunch

**Comment by hyunwoo18** [comment]
Pull request is created.
https://github.com/HEPCloud/decisionengine_modules/pull/301

**Comment by StevenCTimm** [comment]
yes I confirm that Hyunwoo's patch works on fermicloud155

**Comment by StevenCTimm** [comment]
This is now in the release.  Closing.
