### ISSUE TITLE
New version of AccountConstants_my.py not backwards compatible to python2

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#284]
I made a new version of AccountConstants_my.py to remove one of the four AWS accounts. 
It works with the decisionengine_modules 1.4.0 release which is python3, but not with the decisionengine_modules 1.1.0 release which is python2, still running on gpde01 for now.

The file is syntactically correct both in python3 and python2, but when the DEAccountConstants.py routine
in the python2 version attempts to read it in and exec the code to declare the dictionary, it gives an error for unterminated string.    I have not been able to figure out why it doesn't like this file.  Rolling back to the previous version of the file was fine.

This may not be technically a modules code issue, since AccountConstants_my.py is a constants file that lives in 
/etc/decisionengine/modules.conf

But it would be nice to get to the bottom of it.

**Comment by DmitryLitvintsev** [comment]
Can you post this AccountConstants_my.py somewhere?

**Comment by StevenCTimm** [comment]
It's available in the hepcloud-git.fnal.gov git repo to which you have access.  It is also on hepcsvc03 and other dev machines in /etc/decisionengine/modules.conf/AccountConstants_my.py 

https://hepcloud-git.fnal.gov/ECF-GCO/decisionengine-configs/-/blob/master/modules.conf/AccountConstants_my.py

**Comment by StevenCTimm** [comment]
This issue is now moot because all decision engines are upgraded to and running the python3 version.

However I think I see what was happening.

This is the syntax in the python3 version of DEAccountContants.py

    config_dict = None
    with open(constants_file, "r") as f:
        config_dict = eval(f.read())
    return config_dict

(lines 59-62)

The python2 version was doing string.join(f.readlines,"")

The new code is a better way to do it.
