### ISSUE TITLE
Need to be able to add the conversion map to the factory_entries source

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#323]
The source glideinwms/sources/factory_entries.py calls a different path to get to the htcondor bindings 
than what the other two condor-related sources do.

factory_entries.py inherits from htcondor/htcondor_query.py 

instead of htcondor/sources/slots.py as does the NERSC channel.
(which in turn calls htcondor_query).  The latter has the correction_map feature appended which can 
modify the default values of a few parameters.  This is needed because we now have a couple fields
in the factory classads which can either be undefined or STR--namely GLIDEIN_Resource_Slots 
and GLIDEIN_CMSSite.

It may be a bit involved because the factory_entries.py actually does several condor_status calls, one to each factory
but maybe we can just modify the code in some way so that we can pass the correction_map through as well.

**Comment by StevenCTimm** [comment]
This is a bit more specific map-out of the calls:

decisionengine_modules.htcondor.sources.slots (called in Nersc.jsonnet). 
imports decisionengine_modules.htcondor.sources.source.  (which allows for and implements  correction_map)
which imports decisionengine_modules.htcondor.htcondor_query
which imports the actual htcondor python bindings.

decisionengine_modules.glideinwms.sources.factory_entries. (called in channel_aws_config_data)
imports decisionengine_modules.htcondor.htcondor_query --and calls it once per factory
(which then calls the htcondor python bindings)

So what needs to be done is to replace the call in line 71 of factory_entries to htcondor_query
with one to source.py 
and also pass along the correction_map that is in the config file.

There would then be a correction_map added to each factory independently.

        "condor_config": "/etc/condor/condor_config",
        "factories": [
          {
            "collector_host": "cmssrv258.fnal.gov",
            "classad_attrs": [],
            "correction_map": {
               "GLIDEIN_Resource_Slots":'',
               "GLIDEIN_CMSSite":''
            }
          },
          { 
            "collector_host": "fermifactory01.fnal.gov",
            "classad_attrs": []
          },
          {
            "collector_host": "gfactory-2.opensciencegrid.org",
            "classad_attrs": [],
            "constraint": "GLIDEIN_CPUS!=\"auto\" && GLIDEIN_CPUS!=\"node\""
          }

**Comment by hyunwoo18** [comment]
Steve, as we discussed this afternoon, I implemented my patch in factory_entries_new.py
```
[root@hepcsvc03 sources]# pwd
/usr/lib/python3.6/site-packages/decisionengine_modules/glideinwms/sources

[root@hepcsvc03 sources]# diff factory_entries_new.py   factory_entries.py 
64,65c64
< # HK> this get method returns "None" if correction_map is not found inside a factory(which is a dict)
<             correction_map = factory.get('correction_map')
---
> 
71,76d69
< # HK> let's first make sure corretion_map is not None
<                 if not corretion_map:
<                     for eachDict in condor_status.stored_data:
<                         for key, value in correction_map.items():
<                             if eachDict.get(key) is None:
<                                 eachDict[key] = value
```

Please test this and let me know of any errors if any.

**Comment by StevenCTimm** [comment]
At first ( with a couple of typos) it appeared to be working, but then I am not so sure because the values I put in the correction map don't actually end up getting replaced in the dictionary.  Also there's a different exception now too.

**Comment by hyunwoo18** [comment]
Well, Steve, I just now put some print statements in factory_entries.py,
(I see that you copied factory_entries_new.py to factory_entries.py and factory_entries.py.1.6.1 is the original file)
And it looks like, the code seems to load correction_map properly
but condor_status.stored_data itself is empty
```
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug 1
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug begin
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - {'GLIDEIN_CMSSite': '', 'GLIDEIN_Resource_Slots': ''}
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug end
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - {}
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - <class 'dict'>
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug begin
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - {'GLIDEIN_CMSSite': '', 'GLIDEIN_Resource_Slots': ''}
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug end
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - {}
2021-04-02T23:48:02-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - <class 'dict'>
2021-04-02T23:48:03-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug begin
2021-04-02T23:48:03-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - {'GLIDEIN_CMSSite': '', 'GLIDEIN_Resource_Slots': ''}
2021-04-02T23:48:03-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - HK debug end
2021-04-02T23:48:03-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - {}
2021-04-02T23:48:03-0500 - root - factory_entries - 19080 - FactoryEntries - ERROR - <class 'dict'>
```

**Comment by StevenCTimm** [comment]
OK I will check further.,. the data blocks from Factory_Entries* are getting populated by the routine so somewhere there is data there..only question is do we have the right variable name that we are looping through.. thanks for the diagnostic, that helps.

**Comment by StevenCTimm** [comment]
OK I see the problem--we are trying to apply the correction_map before the condor_status.load method is called and so there is nothing in condor_status.stored_data yet.  I will just move the correction_map code below that, after the retry_wrapper.

**Comment by StevenCTimm** [comment]
yes now the correction table is working and the two fields I corrected are now type "str" as desired.
Now to see if we have any other bad types that also need to be corrected.

**Comment by hyunwoo18** [comment]
> OK I see the problem--we are trying to apply the correction_map before the condor_status.load method is called and so there is nothing in condor_status.stored_data yet. I will just move the correction_map code below that, after the retry_wrapper.

Good catch!

**Comment by StevenCTimm** [comment]
It has now gotten as far as requesting glideins from the factory and I am not getting any exceptions on undefined values now.
If I get the rest of the setup going I will suggest that we make a pull request on Monday.

**Comment by hyunwoo18** [comment]
I created a pull request (https://github.com/HEPCloud/decisionengine_modules/pull/324)
but it seems like it the creation failed because of missing approval within github.
I managed to assign a review process to you Steve. See if you got an email from github.

**Comment by hyunwoo18** [comment]
I will create a new ticket for the unit test issue that Pat pointed out in https://github.com/HEPCloud/decisionengine_modules/pull/324#discussion_r611657638
because I do not have time to work on that this week and Steve seems to need this new correction_map right away.
So, let's close this issue for now.

**Comment by mambelli** [comment]
@StevenCTimm, @hyunwoo18, If a key is in the correction map, this code (if eachDict.get(key) is None) both adds an entry if the key is missing and replaces values that are None. Please confirm that this is what you want

**Comment by StevenCTimm** [comment]
Yes this is what we want--to replace the None values and to add it if the key is missing.
The problem with None in Pandas is that it has type NoneType and thus can't be used in string or numeric pandas
expressions in queries, that's why we have to get rid of it for values we are selecting on.

**Comment by StevenCTimm** [comment]
This fix supposedly was supposed to be included in 1.6.2 but it is not.

**Comment by StevenCTimm** [comment]
This is now in the 1.6.2 that we have been running on hepcsvc03.. as soon as it is deployed in production 
we will close this issue.

**Comment by StevenCTimm** [comment]
This is now deployed in production.  Closing this issue.
