### ISSUE TITLE
Follow up for 323 unit test inside correction map logic

### ISSUE THREAD

**Issue by hyunwoo18** [HEPCloud/decisionengine_modules#325]
As commented at the end of https://github.com/HEPCloud/decisionengine_modules/issues/323,
Pat Riehecky pointed out in #324 (comment) that we need to put a unit test logic.
This argument also applies to the original files where I put the correction map logic.

**Comment by hyunwoo18** [comment]
I started working on this issue today and examined current unit test logic 
which is decisionengine_modules/tests/test_factory_entries.py 
and struggled to figure out what Pat meant by his comment.
Isn't decisionengine_modules/tests/test_factory_entries.py enough?
Why do we need a new test logic?
His original comment was 
```
Code Cov is reporting that line 82 isn't covered by any tests. Can we get a unit test to trigger this line?
```
Do we need a unit test just for this specific line when we already have a test for the entire file
(decisionengine_modules/tests/test_factory_entries.py)??

**Comment by hyunwoo18** [comment]
Okay, today I first communicated further with Pat in the morning
in order to find out what he actually wanted
and since then, have been trying to come up with a new test that cover this line 82 in question 
or the entire new block

```
if correction_map is not None:
                    for eachDict in condor_status.stored_data:
                        for key, value in correction_map.items():
                            if eachDict.get(key) is None:
                                eachDict[key] = value
```

But my current conclusion is, we really don't need test this code because I believe this block of code
will never fail.
Namely, in the line 82 eachDict[key] = value, we do not get the value of a directory item that might not exist
rather we just assign a predefined value to a key that is guaranteed to exist by the line 81 (if eachDict.get(key) is None:)

Or if I still misunderstood Pat's comment, I could just add a new test file which does
1. contact a factory (like fermifactory01.fnal.gov) 
2. retrieve GLIDEIN_Resource_Slots or GLIDEIN_CMSSite
3. make sure for those entries whose values for these attributes are "undefined", the corrected values are empty string (as specified in the correction_map).
If this proposal is acceptable, I can start coding this new file soon.

**Comment by hyunwoo18** [comment]
I leave this comment as my record:
```
[root@hepcsvc03 ~]# condor_status -any -constraint 'MyType=="glidefactory"' -af GLIDEIN_CMSSite GLIDEIN_Resource_Slots -pool fermifactory01.fnal.gov

T3_US_SDSC undefined
T3_US_PSC undefined
T3_US_NERSC undefined
T3_US_NERSC GPUs,1,type=main
T3_US_NERSC undefined
T3_US_SDSC undefined
T3_US_TACC undefined
T1_US_FNAL undefined
T1_US_FNALTEST undefined
undefined undefined
undefined undefined
undefined undefined
```

I even wrote a simple Python code based on factory_entries.py
```
[root@hepcsvc03 ~]# cat hktest.py
from pprint import pprint
from decisionengine_modules.htcondor import htcondor_query

constraint = '(glideinmytype=="glidefactory")'

condor_status = htcondor_query.CondorStatus( subsystem_name='any',  pool_name='fermifactory01.fnal.gov', group_attr=['GLIDEIN_GridType'])

condor_status.load( constraint, ['GLIDEIN_Resource_Slots'], '/etc/condor/condor_config' )
pprint( condor_status.stored_data )
```

And when I run this, I get the same results
```
[root@hepcsvc03 ~]# python3 hktest.py
[{'GLIDEIN_Resource_Slots': None},
 {'GLIDEIN_Resource_Slots': 'GPUs,1,type=main'},
 {'GLIDEIN_Resource_Slots': None},
```

**Comment by hyunwoo18** [comment]
Finally I managed to implemented a new test logic in test_factory_entries.py 
to test the new correction_map logic in glideinwms/source/factory_entries.py.

Created a PR 
https://github.com/HEPCloud/decisionengine_modules/pull/337

**Comment by hyunwoo18** [comment]
Closed the PR 337 due to an error while squashing the commits,
Created a new branch (t325new) and a new PR 338

**Comment by mambelli** [comment]
merged
