### ISSUE TITLE
DE modules entrypoint script always pick DE default branch, this becomes an issue when testing DE modules branches

### ISSUE THREAD

**Issue by vitodb** [HEPCloud/decisionengine_modules#333]
Currently DE modules entrypoint script always pick DE default branch as dependency, this becomes an issue when testing a DE modules branch that is not compatible with DE default branch.
This behavior is due to this line in the  [entrypoint script](https://github.com/HEPCloud/decisionengine_modules/blob/master/package/ci/python3-entrypoint.sh#L12).
At this time DE modules unit tests for branch 1.6 on Jenkins are [failing](https://buildmaster.fnal.gov/buildmaster/view/Decision%20Engine/job/decisionengine_modules_pipeline/987/artifact/pytest.log).
A solution to this could be to update the entrypoint script to optionally allow the use of a specific branch/revision for DE.

**Comment by mambelli** [comment]
Fixed in master and 1.6
