### ISSUE TITLE
Name convention on bill_calculator_hep vs. billing_calculator_hep

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#348]
With the port of the bill-calculator-hep to the hepcloud git repo, it has changed
names in a confusing way.

The pip3 package as stored in pypi is called bill-calculator-hep
The  dist-info directory is bill_calculator_hep-0.1.2.dist-info
But the actual source directory that's untarred is billing_calculator_hep.

Everything works, the code is functional, but it seems a big inconsistency to have the dist-info directory and the package name, not match the top level dir of the package.

**Comment by mambelli** [comment]
The modules' packaging should be updated once the naming has been fixed.

The repository has also still both the directories `bill_calculator_hep` and `src/billing_calculator_hep`. I think the former is obsolete and should be deleted. If the files were copied and the history of the old ones is important, the developers may consider updating the files in the old place, delete the files in the new place, and use `git mv` to the new directory.

**Comment by StevenCTimm** [comment]
In version 0.1.4 Maria has made all the relevant import directories be bill-calculator-hep again.
Need to change the modules back to import bill-calculator-hep rather than billing-calculator-hep.

**Comment by StevenCTimm** [comment]
We are holding production at billing-calculator-hep 0.1.2 until this is done.

**Comment by StevenCTimm** [comment]
This is resolved in 0.1.4 version of the bill-calculator-hep 0.1.4
