### ISSUE TITLE
Channel global config design

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#36]
* Come up with the requirements for the global channel config
* Identify a draft of the config settings based on the current channels for FNAL deployment and glideinwms frontend and come up with initial draft of channel global config. We will iterate over this draft.

**Comment by DmitryLitvintsev** [comment]
Imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/110

**Comment by StevenCTimm** [comment]
Presume that this will be covered by the framework development that is now ongoing for the total redesign of the configuration system.

**Comment by StevenCTimm** [comment]
The features for global config design of channels now exist in the current release but we have not yet tested the include features in integration, holding this ticket open until we can do that.

**Comment by StevenCTimm** [comment]
Vito Dibenedetto has now tested these features and showed me the results, I am content with this.
Now closing this issue.
