### ISSUE TITLE
Test decision engine with SciTokens and IDTokens

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#382]
We request coordination between DE developers and glideinwms developers to describe the procedure
of what it will take to get the Decision Engine to acquire and generate SciTokens for glideinwms submissions 
to remote sites, and IDTokens to authenticate the glideins to the hepcloud user pools.
Decision Engine runs the latest glideinwms frontend libraries but it is not clear if other things 
are needed to make it work.

If modifications to the code are necessary, this should be considered a request to make them,.

The drop dead time by which this must be done, is when OSG transitions the hosted-CE's in front of the 
XSEDE resources to be tokens only.  This may be happening as early as 2Q 2022.

**Comment by mambelli** [comment]
Depends on #384 and #385

**Comment by StevenCTimm** [comment]
I am now configuring fermicloud435 (DE 1.7.4) and fermicloud467 (DE 2.0.2) to start using idtokens and SciTokens.. thus 
far fermicloud435 has been able to talk to the factory using idtokens..

**Comment by StevenCTimm** [comment]
This has now been done, successfully.
We have tokens in production everywhere.
