### ISSUE TITLE
Exceptions thrown by various modules that currently set channels to OFFLINE

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#46]
We have started to discuss error handling in decision engine. 
Here I want to document some of the exceptions I have run into on my test system:

```
StartdManifests - ERROR - error running source StartdManifests <class 'decisionengine_modules.htcondor.htcondor_query.QueryError'> Error querying pool cmssrv274.fnal.gov using python bindings: Failed communication with collector.
```

```
NerscJobInfo - ERROR - error running source NerscJobInfo <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', error(110, 'Connection timed out'))
```

General discussion: how errors must be handled?

1) in the modules, and pertinents calls retried within interface functions (like `acquire` or `transform` or `publish`)

2) or by framework - exceptions are caught by modules and re-throen as some sort "RetriableExcption". Having caught this exception `TaskManager` can either retry the whole call or skip with error message till next cycle  w/o declaring channel OFFLINE

to give example 

1) : 

```
    def get_some_data(self):
        # throws ssl.Error say

    def acquire(self):
       while True:
          try:
            ...
            data = self.get_some_data()
            break
          catch ssl.Error as e:
            if tries < RETRIES:
              time.sleep(TIMEOUT);
```

vs 2):

```
    def get_some_data(self):
        # throws ssl.Error say

    def acquire(self):
        try:
            ...
            data = self.get_some_data()
            break
         catch ssl.Error as e:
            raise RetriableError(e)

```

Disadvantage of (1) - it makes things messy in modules and there is danger to interfere with advertized 
schedule period which TaskManager enforces. 

(2) outsources error handling decision to TaskManager but things look cleaner. Modules know what kind of exception
to raise. Like just three kinds : Fatal, Ratriable, RuntimeException (latter more to catch code bugs). And TaskManager would do expected actions based on exception type. 

Dmitry

**Comment by DmitryLitvintsev** [comment]
Imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/134

**Comment by hyunwoo18** [comment]
I am thinking of this ticket next because this is a bit related to the one that I have been working (198)

**Comment by StevenCTimm** [comment]
The new framework requirement say that the framework must be configurable to (1) retry the failed operation (2) use the old block instead (3) fail and throw an exception.. presumably this will be part of the error handling work that I believe Pat Riehecky will be assigned to.

**Comment by StevenCTimm** [comment]
Once the exception handling for publishers is pushed to the next release, 1.8. or 2.0 then there are no further exceptions that should be handled and this one can be closed.

**Comment by StevenCTimm** [comment]
This has now been pushed to the current release.
Closing this ticket.
