### ISSUE TITLE
Feature request: GCE Billing Info--have it return 24hr per-hour cost rate--low priority

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#51]
Have the GCE Billing Info source return the average per/hour cost rate over the last 24 hour period.  This is low priority but the code to do it is available in the standalone GCEBillingAlarms.py in the bill-calculator rpm.  There is only a limited amount you can do with this info in the DE because it lags so far behind.  But should do it to have symmetry with the AWS case and hopefully also they will be able to give us billing faster.

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/167

**Comment by StevenCTimm** [comment]
This is moot now because Namratha has totally rewritten the routine to do a totally different thing than it did before.
