### ISSUE TITLE
project id handling for XSEDE sites.

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#57]
The current configuration of the decision engine, like the frontend that preceded it, allows for a credential type of 
"grid_proxy+project_id" for example

 <credential absfname="/etc/gwms-frontend/proxies/cms_proxy" project_id="fna101" security_class="frontend" trust_domain="grid" type="grid_proxy+project_id"/>

But this can only work when the VO (in this case CMS) has the same project ID on all xsede factory that
have mode grid_proxy+project_id authentication.  Some of the project_id are hidden from visibility by
the hosted CE's (PSC and TACC), others are masked by ssh'ing into different users (NERSC).. but we know of
2 so far (ohio supercomputing center, and SDSC) where we have to send a project_id directly.  There will probably 
be more.

Will need a better way to distribute project ID's to xsede sites without having to create a 
(frontend_group ; factory_entry) set for each.

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/179

**Comment by StevenCTimm** [comment]
This is moot because all project id's are stored in the hosted CE now, closing this
