### ISSUE TITLE
Update Nersc Allocation Info source for new NERSC API

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#62]
NERSC has totally changed the method by which accounting info is accessed via the newt API. It is now necessary to use the python requests module.

A full worked example is available at https://gist.github.com/shreddd/11be2778831fcc1ca239f96c1420239e

I have worked through all the commands interactively in the above URL and verified that they work.
It will however be necessary to do a near total rewrite of the existing NerscAllocationInfo source to use these
new methods.  

NERSC notified us in advance that the new API was coming but they did not tell us the old one would be frozen in time
as of January 14, 2020.  So we are now not getting any new allocation info.

To be clear there are two independent pieces of code that access this API
NERSC/sources/NerscAllocationInfo.py originally written by Dmitry Litvinsev,
and allocation_monitor.py in the "probescollection" RPM that runs on hepcsvc01 outside the Decision Engine.
The former was written from scratch by Dmitry using the modern python requests model,
after looking at the latter, originally written by a summer student 3 years ago, and deciding
it was easier to start from scratch than to fix the code.
We expect that merging the new commands into the NerscAllocationInfo.py would take a day or two of work at most.  Changing the second routine may be harder and it may well be wise to do a complete rewrite
based on the DE code.

**Comment by DmitryLitvintsev** [comment]
https://github.com/HEPCloud/decisionengine_modules/pull/15
https://github.com/HEPCloud/decisionengine_modules/pull/196

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/187

**Comment by StevenCTimm** [comment]
Test of the 1.1.0 py27 release show that this code is working correctly and we are getting the correct values from NERSC now,
