### ISSUE TITLE
Change all DE publishers to add the DE name to the namespace so that we don't overwrite graphite

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#65]

**Comment by DmitryLitvintsev** [comment]
https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/190

**Comment by hyunwoo18** [comment]
I discussed with Steve Timm today, Steve thinks that I will be able to try this issue.
I did some investigation today and the following is what I found out from a quick research:

decisionengine_modules/graphite/publishers/generic_publisher.py shows the following
```
    def publish(self, data_block):
        if self.graphite_host and self.publush_to_graphite:
            end_point.send_dict( self.graphite_context(data)[0], self.graphite_context(data)[1] ..)
````

and from my experience of working on another graphite probes, I know that
the first argument to send_dict() is the namespace.
and from the following codes,
```
From decisionengine_modules/AWS/publishers/AWS_burn_rate.py 
class AWSBurnRatePublisher(publisher):
    def graphite_context(self, data_block):
        d = {}
        d['FERMILAB.BurnRate'] = data_block.loc[0, 'BurnRate'].item()
        return self.graphite_context_header, d
...........
From decisionengine_modules/graphite/publishers/generic_publisher.py 
class GenericPublisher(Publisher.Publisher):
    def __init__(self, config):
        self.graphite_context_header = config.get('graphite_context', ...)
```
I could deduce that the namespace information comes from the "graphite_context" in config files.
So, I look at the following two files in hepcsvc03:/etc/decicionengine/config.d/
```
more AWS_Calculations_with_source_proxy.conf
  "publishers" : {
      "AWSPricePerformance" : {
          "parameters" : {"graphite_host": "hepcmetrics.fnal.gov",
                          "graphite_context":"hepcloud_priv.de.aws"

      "AWSFigureOfMerit" : {
          "parameters" : {"graphite_host": "fifemondata.fnal.gov",
                          "graphite_context":"hepcloud.de.hepcsvc03.aws"

      "AWSBurnRate" : {
          "parameters" : {"graphite_host" : "hepcmetrics.fnal.gov",
                          "graphite_context" : "hepcloud_priv.de.hepcsvc03.aws"
  },

more Gce.conf
  "publishers" : {
    "GCEPricePerformancePublisher": { 
      "parameters" : {    "graphite_host": "hepcmetrics.fnal.gov",
                          "graphite_context": "hepcloud_priv.de.gce",

    "GCEFigureOfMeritPublisher": {
      "parameters" : {    "graphite_host": "fifemondata.fnal.gov",
                          "graphite_context":"hepcloud.de.gce",

     "GCEBurnRatePublisher": {
       "parameters" : {   "graphite_host": "hepcmetrics.fnal.gov",
                          "graphite_context": "hepcloud_priv.de.hepcsvc03.gce",       },     },
  }

```
At this point, I have a question for Steve:
Did you want each of these publishers to dynamically generate the namespace 
based on both the value of graphite_context from the config file
and the DE?
For example, I could update decisionengine_modules/AWS/publishers/AWS_burn_rate.py
such that this specific publisher can send the data using the following 3 namespaces
- hepcloud_priv.de.hepcsvc03.aws 
- hepcloud_priv.de.cmsde01.aws 
- hepcloud_priv.de.gpde01.aws 

In detail, for this to work, I would have to change the value of graphite_context
for AWSBurnRate in /etc/decicionengine/config.d/AWS_Calculations_with_source_proxy.conf
to hepcloud_priv.de.aws (note current value is hepcloud_priv.de.hepcsvc03.aws)
and make the AWS_burn_rate.py code be able to retrieve the current DE name
and insert this DE name between "hepcloud_priv.de" and "aws"

So, is this what you wanted, Steve?

**Comment by StevenCTimm** [comment]
We would have to look at each individual publisher carefully
If it is as simple as changing the graphite_context correctly in the config file to add the decision engine
name and that works in all six of the affected publishers, then it's easier to just change the config file.

**Comment by StevenCTimm** [comment]
The complete list of publishers is as follows:
AWS/publishers/AWS_burn_rate.py
AWS/publishers/AWS_figure_of_merit.py
AWS/publishers/AWS_generic_publisher.py
AWS/publishers/AWS_price_performance.py
GCE/publishers/GCEBurnRatePublisher.py
GCE/publishers/GCEFigureOfMerit_publisher.py
GCE/publishers/GCEPricePerformance_publisher.py
glideinwms/publishers/job_clustering_publisher.py 
NERSC/publishers/NerscFigureOfMerit_publisher.py

------------
Those that do have a DE field in config
AWS_burn_rate.py
AWS_figure_of_merit.py 
GCEBurnRatePublisher.py
(that doesn't mean the graphs are necessarily right)


The ones currently affected by zigzag:
AWS_price_peformance.py
GCEPricePerformance_publisher.py
GCEFigureOfMerit_publisher.py
glideinwms/publishers/job_clustering_publisher.py
NerscFigureOfMerit_publisher.py 


From my review of the code as I understand it, it appears that if we change the default graphite_context in the configuration for those five publishers we will get the added field  that we need, without further modifications to the code

I propose that we do this first on hepcsvc03's configs and see if it helps.. we may then also have to adjust the corresponding grafana graphs on 
https://hepcmetrics.fnal.gov/d/f1n7BC9mz/price-performance?orgId=1
https://hepcmetrics.fnal.gov/d/rlPS_o6mz/vm-burn-rates?orgId=1
and 
https://landscape.fnal.gov/gco/d/ZcWRzyEik/decision-engine-home?orgId=1&refresh=5m&from=now-7d&to=now

**Comment by StevenCTimm** [comment]
I attempted to modify all the configurations on hepcsvc03 to make graphite_context be 
hepcloud.de.hepcsvc03.*
There were 5 publishers that were affected, the ones above.  I do not see any difference in the output of the graphs.  We will have to examine the dashboards above one by one to make sure that they can deal with the new field in the graphite context.   if they can't be adjusted then we will have to look more carefully at the code itself.  I would appreciate if someone who is knowledgeable in Grafana dashboards can help with this.
 I

**Comment by StevenCTimm** [comment]
Changing all the graphite_context fields in all decision engine config files, plus changing all of the configurations of the above dashboards, now makes it so we don't have any more zigzag dashboards.

This issue can be closed.

I am closing it.
