### ISSUE TITLE
Nersc channel goes OFFLINE on a timeout

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#70]
2) NERSC channel also aborted on a timeout

2018-12-03 07:56:46,824 - decision_engine - TaskManager - NerscJobInfo - ERROR - error running source NerscJobInfo <class 'requests.exceptions.ConnectionError'> ('Connection aborted.', error(110, 'Connection timed out'))

Basically we need to have a discussion as to how timeouts should be handled. Requiring manual intervention after one timeout seems a bit extreme to me,

**Comment by DmitryLitvintsev** [comment]
timm @timm marked this issue as related to #110 3 months ago

**Comment by DmitryLitvintsev** [comment]
imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/121

**Comment by shreyb** [comment]
Code submitted for review.  Basically, we use urllib3's Retry class to implement a configurable retry loop.

**Comment by shreyb** [comment]
@DmitryLitvintsev  - can this issue be closed at this point?

**Comment by DmitryLitvintsev** [comment]
yes. Closing.
