### ISSUE TITLE
Stale NERSC data block used by resource request channel

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#86]
'Due to a new manifestation of the factory bug, all NERSC figures of merit became null.  

Thus we have a situation where the Nersc channel is producing a null 
Nersc_Figure_Of_Merit data block but the Resource_Request channel
is still holding on to the old one..
```
[root@hepcsvc03 decisionengine]# de-client --print-product Nersc_Figure_Of_Merit
Product Nersc_Figure_Of_Merit:  Found in channel resource_request
+----+-----------------------------------+-----------------+
|    | EntryName                         |   FigureOfMerit |
|----+-----------------------------------+-----------------|
|  0 | CMSHTPC_T3_US_NERSC_Edison        |      0.229787   |
|  1 | CMSHTPC_T3_US_NERSC_Cori          |      0.12       |
|  2 | CMSHTPC_T3_US_NERSC_Edison_shared |      0.666768   |
|  3 | CMSHTPC_T3_US_NERSC_Cori_shared   |      0.00118248 |
|  4 | CMSHTPC_T3_US_NERSC_Cori_KNL      |      0.006      |
+----+-----------------------------------+-----------------+
 Found in channel Nersc
		'taskmanager_id=2085 or generation_id=1019 or key=Nersc_Figure_Of_Merit not found'

```
Thus the decision engine is still trying to send stuff to NERSC even though it should move on to other resources such as AWS or GCE.

This indicates some issue with a data block expiration problem that
we need to understand.

(actually I believe it is not even requesting new resources at NERSC because it thinks it has enough, but it doesn't.  I base that on the fact that the monitoring classads all show undefined and they wouldn't do so if we were in fact requesting new resources there.)

**Comment by DmitryLitvintsev** [comment]
Imported from GitLab: https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/143

**Comment by StevenCTimm** [comment]
This is now moot given the restructuring of the way that sources are run in DE 2.0.  Closing.
