### ISSUE TITLE
Provide a means to insert default values for classad attributes

### ISSUE THREAD

**Issue by DmitryLitvintsev** [HEPCloud/decisionengine_modules#88]
htcondor_query will select attributes listed in the classad_attrs list. If it is empty list, entire classad is picked up. However given the attr name is used as dataframe column name, there is need to have default value for some attrs in case they are no present. We need to provide additional configuration parameter for every module.

**Comment by DmitryLitvintsev** [comment]
Imported from GitLab:https://hepcloud-git.fnal.gov:8443/hepcloud/decisionengine_modules/issues/145

**Comment by StevenCTimm** [comment]
This is related to issue #255 above--In this one I only asked for a default value but now I also want the capacity to override the type of the variable as well.

**Comment by StevenCTimm** [comment]
This is now complete and running in production.
